### ISSUE TITLE
TypeError: _jsxDEV is not a function

### ISSUE THREAD

**Issue by lorenzejay** [hashicorp/next-mdx-remote#324]
Getting an error on next v13.0.2 and next-mdx-remote v4.2.0

Everything works fine till I insert
```jsx
<MDXRemote {...source} components={{ Image }} />
```

<img width="959" alt="Screenshot 2022-12-26 at 7 41 50 PM" src="https://user-images.githubusercontent.com/63378463/209607733-727d3ba0-be0b-499f-a45a-e413761d942c.png">

**Comment by mabdh** [comment]
This issue seems is likely to be solved by this https://github.com/hashicorp/next-mdx-remote/issues/307#issuecomment-1363433316

**Comment by lorenzejay** [comment]
> This issue seems likely to be solved by this [#307 (comment)](https://github.com/hashicorp/next-mdx-remote/issues/307#issuecomment-1363433316)

Yes that worked for me. For reference, setting `development: false` will fix.

**Comment by devzom** [comment]
Mentioned here https://stackoverflow.com/questions/74807529/jsxdev-is-not-a-function-when-using-mdxremote

**Comment by BRKalow** [comment]
Hi y'all, this should be addressed by https://github.com/hashicorp/next-mdx-remote/pull/323, try out 4.2.1 and let me know!

**Comment by itsnitinr** [comment]
Can confirm that `4.2.1` works and solves this issue. Thanks!

**Comment by blvdmitry** [comment]
Interesting enough, I've updated to the latest next-mdx-remote with renovate notification and it started breaking with something that seems to be an opposite error. Do you think you might know what could cause it or should share more information about the setup in a separate issue?

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/887379/211386816-3ccd418f-9e6a-40b7-aee8-663a0938b11b.png">

**Comment by B2o5T** [comment]
same problem for me as @blvdmitry

**Comment by BRKalow** [comment]
if you do a full re-install this should be fixed:
```
npm uninstall next-mdx-remote && npm install next-mdx-remote
```

**Comment by blvdmitry** [comment]
Tried 5 different ways of uninstalling because I use yarn and lerna and it worked in the end. Thanks for the tip!

**Comment by teddybee** [comment]
This issue still exist with "next-mdx-remote": "4.3.0"

**Comment by auduongtuan** [comment]
this issue still exist with "next-mdx-remote": "4.3.0" and "next": "^13.1.6" T_T

**Comment by Eliot00** [comment]
this issue still exist with
    "next": "^13.1.2",
    "next-mdx-remote": "^4.4.1",

**Comment by sebanovo** [comment]
alternative solution: development: process.env.NODE_ENV === 'development',
